server:
  port: 8080

spring:
  datasource:
    name: mysql
    url: jdbc:mysql://localhost:3306/bda?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=CTT
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.example.bda.pojo
  global-config:
    db-column-underline: true
  configuration:
    mapUnderscoreToCamelCase: true

logging:
  level:
    com:
      example:
        demo:
          mapper: debug

